### ISSUE TITLE
ValueError: Captcha (ip reputation ?)

### ISSUE THREAD

**Issue by HawkLiking** [VeNoMouS/cloudflare-scrape-js2py#25]
I know it can be related to https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/24 but i have already try to update all packages and others solutions.

I think it's an IP reputation problem, I make request every 2 minutes, maybe it's the problem (it works on my personal computer, different installation but...). But I want to be sure it comes from that

Here is my test code:
```python
import cfscrape

cf = cfscrape.create_scraper()
#cf.debug = True

def getPage(urlpage):
  return cf.get(urlpage, timeout=15)

getPage("https://pro-src.com/")
```

Here is my debug-less output:
```bash
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    getPage("https://pro-src.com/")
  File "test.py", line 7, in getPage
    return cf.get(urlpage, timeout=15)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 107, in request
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 160, in solve_cf_challenge
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 100, in request
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 64, in is_cloudflare_challenge
ValueError: Captcha
```

I sent the debug full output to @VeNoMouS venom [at] gen-x.co.nz

Here is my pip freeze ouput:
```bash
certifi==2019.3.9
cfscrape==2.0.3
chardet==3.0.4
cryptography==1.7.1
enum34==1.1.6
idna==2.8
ipaddress==1.0.17
Js2Py==0.60
keyring==10.1
keyrings.alt==1.3
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
pyjsparser==2.5.2
pytz==2019.1
pyxdg==0.25
requests==2.21.0
requests-toolbelt==0.9.1
SecretStorage==2.3.1
six==1.12.0
tzlocal==2.0.0b1
urllib3==1.24.1
```

**Comment by HawkLiking** [comment]
It doesn't work with a total other IP (different country) , and same test script, same config (debian) , and i never made cloudflare request with that one...

**Comment by HawkLiking** [comment]
OOOOOK, i'm sorry for this issue

It works on python3 but not on python2.7, maybe related to this issue comment https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/20#issuecomment-481199292

Sorry you can close this issue, have a good day :) 👍

**Comment by HawkLiking** [comment]
I re-open it because it can be interesting fact:

cfscrape was working from the beginning in py2.7 with my script, and stoped working on Friday 12th April, 20h34 (UTC+1)

Maybe this is due to a cloudflare change... ?

Anyway, it is working in py3

**Comment by VeNoMouS** [comment]
Sorry @HawkLiking what works in py3 and what doesnt work in py2?

**Comment by VeNoMouS** [comment]
ah just found your 2.7 debug out , thanks for that :) will go over it later... just got flew back yesterday afternoon

**Comment by VeNoMouS** [comment]
I had a quick glance... very interesting.. you got hit with a challenge, you solved it cf hit you back with a captcha ... never seen that... 

I am wanting to add in some new features to help combat this... 

I do have a question... with your code are you in a loop? or do you run your code every N minutes?

if you're running in a loop you should really setup a __requests__ sesssion() and pass that off to cfscrape... you'll solve the challenge once and not get prompted till cf considers the session no longer valid... which is AGGGGES...

**Comment by VeNoMouS** [comment]
Ah... wait your using @pro-src as your source? hahaha he's forced the captcha on... bad test ;P

**Comment by HawkLiking** [comment]
I run my code every N minutes (crontab), but yes, i should save the cookie and the UA in a file and use it each time

I used pro-src for the test, but i was having this error on all cloudflare protected websites

**Comment by pro-src** [comment]
The CAPTCHA hasn't been on for a while.

**Comment by VeNoMouS** [comment]
@HawkLiking I'll have a look later today ok mate? its monday morning for me atm, have to do my day job

**Comment by HawkLiking** [comment]
No problem take your time, I bump my code to py3 for the moment. But as this error seems new (first time you see that), I am curious to know what has changed :)

**Comment by pannal** [comment]
I'm experiencing the same right now. [Sub-Zero](https://github.com/pannal/Sub-Zero.bundle), which is restricted to Python 2.7 from the Plex environment.

I can run tests with my local 2.7, though, just not with the older 2.7 inside the Plex environment. That one instantly yields the Captcha error.

**Comment by pro-src** [comment]
@pannal The Plex plugin framework is complete and utter trash. I feel sorry for you. :rofl:

**Comment by pannal** [comment]
Yes, it is. I was able to make cfscrape work, though. Somehow it doesn't work anymore, though.

Investigating.

**Comment by pannal** [comment]
@pro-src I'm hard-pressed here to make what's causing the issue. 

Working:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): subscene.com:443
DEBUG:urllib3.connectionpool:https://subscene.com:443 "GET /subtitles/title?q=The+Orville+-+Second+Season HTTP/1.1" 503 None
DEBUG:cfscrape:OrderedDict([('s', u'0d74a119e031290101768499296edd8a7c7d3243-1555650624-1800-AUduUwq2Q6w3M1c1hmz/u/hMgBBuHR0aFqRNkL5ZJFVVzjCQxhnnZsEX0yN88798I4q42SwY2o+TSam3V4CWibnRNxXGbCgv0QgfdH7gJ3uC+cIQ5CaGDMxRnY4D8VcAxYP2FvoFZcX/zJJXM+Lr8ZkldxfRVg0coViPwyx+eUmgbP9fpCfPPSFNflCClTGXMQ=='), ('jschl_vc', u'08567fbdc8a77941c4c4c04bd0795e0b'), ('pass', u'1555650628.109-3/eL/yoDU2')])
DEBUG:cfscrape:C: {'headers': {'Referer': u'https://subscene.com/subtitles/title?q=The+Orville+-+Second+Season'}, 'allow_redirects': False, 'params': OrderedDict([('s', u'0d74a119e031290101768499296edd8a7c7d3243-1555650624-1800-AUduUwq2Q6w3M1c1hmz/u/hMgBBuHR0aFqRNkL5ZJFVVzjCQxhnnZsEX0yN88798I4q42SwY2o+TSam3V4CWibnRNxXGbCgv0QgfdH7gJ3uC+cIQ5CaGDMxRnY4D8VcAxYP2FvoFZcX/zJJXM+Lr8ZkldxfRVg0coViPwyx+eUmgbP9fpCfPPSFNflCClTGXMQ=='), ('jschl_vc', u'08567fbdc8a77941c4c4c04bd0795e0b'), ('pass', u'1555650628.109-3/eL/yoDU2'), ('jschl_answer', '133.5883915151')])}
DEBUG:cfscrape:Z: OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')]), 'https://subscene.com/cdn-cgi/l/chk_jschl', 'GET', (), {'headers': {'Referer': u'https://subscene.com/subtitles/title?q=The+Orville+-+Second+Season'}, 'allow_redirects': False, 'params': OrderedDict([('s', u'0d74a119e031290101768499296edd8a7c7d3243-1555650624-1800-AUduUwq2Q6w3M1c1hmz/u/hMgBBuHR0aFqRNkL5ZJFVVzjCQxhnnZsEX0yN88798I4q42SwY2o+TSam3V4CWibnRNxXGbCgv0QgfdH7gJ3uC+cIQ5CaGDMxRnY4D8VcAxYP2FvoFZcX/zJJXM+Lr8ZkldxfRVg0coViPwyx+eUmgbP9fpCfPPSFNflCClTGXMQ=='), ('jschl_vc', u'08567fbdc8a77941c4c4c04bd0795e0b'), ('pass', u'1555650628.109-3/eL/yoDU2'), ('jschl_answer', '133.5883915151')])}
DEBUG:urllib3.connectionpool:Resetting dropped connection: subscene.com
DEBUG:urllib3.connectionpool:https://subscene.com:443 "GET /cdn-cgi/l/chk_jschl?s=0d74a119e031290101768499296edd8a7c7d3243-1555650624-1800-AUduUwq2Q6w3M1c1hmz%2Fu%2FhMgBBuHR0aFqRNkL5ZJFVVzjCQxhnnZsEX0yN88798I4q42SwY2o%2BTSam3V4CWibnRNxXGbCgv0QgfdH7gJ3uC%2BcIQ5CaGDMxRnY4D8VcAxYP2FvoFZcX%2FzJJXM%2BLr8ZkldxfRVg0coViPwyx%2BeUmgbP9fpCfPPSFNflCClTGXMQ%3D%3D&jschl_vc=08567fbdc8a77941c4c4c04bd0795e0b&pass=1555650628.109-3%2FeL%2FyoDU2&jschl_answer=133.5883915151 HTTP/1.1" 302 159
DEBUG:cfscrape:R: <Response [302]>
DEBUG:cfscrape:SH: OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')])
DEBUG:cfscrape:Z: OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')]), u'https://subscene.com/subtitles/title?q=The+Orville+-+Second+Season', 'GET', (), {'allow_redirects': True}
DEBUG:urllib3.connectionpool:Resetting dropped connection: subscene.com
DEBUG:urllib3.connectionpool:https://subscene.com:443 "GET /subtitles/title?q=The+Orville+-+Second+Season HTTP/1.1" 200 None
DEBUG:cfscrape:Z: OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')]), u'https://subscene.com/subtitles/the-orville-second-season', 'GET', (), {'allow_redirects': True}
DEBUG:urllib3.connectionpool:Resetting dropped connection: subscene.com
```

Not working:
```
2019-04-19 07:11:13,605 (7fb47ffff700) :  DEBUG (logger:28) - urllib3.connectionpool: Starting new HTTPS connection (1): subscene.com:443
2019-04-19 07:11:13,717 (7fb47ffff700) :  DEBUG (logger:28) - urllib3.connectionpool: https://subscene.com:443 "GET /subtitles/title?q=The+Orville+-+Second+Season HTTP/1.1" 503 None
2019-04-19 07:11:17,727 (7fb47ffff700) :  DEBUG (logger:28) - cfscrape: OrderedDict([('s', u'3f2f9cf24d16afd7eca75809808e2a57e20e64ac-1555650673-1800-AcnjJ51Hp0AZZrd5+Q9gVvB45iFmJcBfGPyJEgAxTFYoTX9XsSwHDtdRaEuj3eoB7V/1LhjRJqOHi6A9k3Vfmd/ts6IybDyjkh+erSqh/rMo0bi4RWJ5MC5k7+ScHdV3uZytgZZR5/KM4Px0/bkflKHE8fCxqn4rN0nGbZIXuBzxPRPK7bzGLU40C083ltx3cg=='), ('jschl_vc', u'e79dbe851486c8da3857ce74fd44b075'), ('pass', u'1555650677.709-qQIFP/fEcq')])
2019-04-19 07:11:18,164 (7fb47ffff700) :  DEBUG (logger:28) - cfscrape: C: {'headers': {'Referer': u'https://subscene.com/subtitles/title?q=The+Orville+-+Second+Season'}, 'allow_redirects': False, 'params': OrderedDict([('s', u'3f2f9cf24d16afd7eca75809808e2a57e20e64ac-1555650673-1800-AcnjJ51Hp0AZZrd5+Q9gVvB45iFmJcBfGPyJEgAxTFYoTX9XsSwHDtdRaEuj3eoB7V/1LhjRJqOHi6A9k3Vfmd/ts6IybDyjkh+erSqh/rMo0bi4RWJ5MC5k7+ScHdV3uZytgZZR5/KM4Px0/bkflKHE8fCxqn4rN0nGbZIXuBzxPRPK7bzGLU40C083ltx3cg=='), ('jschl_vc', u'e79dbe851486c8da3857ce74fd44b075'), ('pass', u'1555650677.709-qQIFP/fEcq'), ('jschl_answer', '13.6186827233')])}
2019-04-19 07:11:18,164 (7fb47ffff700) :  DEBUG (logger:28) - cfscrape: Z: OrderedDict([('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'), ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Connection', 'close'), ('Upgrade-Insecure-Requests', '1')]), 'https://subscene.com/cdn-cgi/l/chk_jschl', 'GET', (), {'headers': {'Referer': u'https://subscene.com/subtitles/title?q=The+Orville+-+Second+Season'}, 'allow_redirects': False, 'params': OrderedDict([('s', u'3f2f9cf24d16afd7eca75809808e2a57e20e64ac-1555650673-1800-AcnjJ51Hp0AZZrd5+Q9gVvB45iFmJcBfGPyJEgAxTFYoTX9XsSwHDtdRaEuj3eoB7V/1LhjRJqOHi6A9k3Vfmd/ts6IybDyjkh+erSqh/rMo0bi4RWJ5MC5k7+ScHdV3uZytgZZR5/KM4Px0/bkflKHE8fCxqn4rN0nGbZIXuBzxPRPK7bzGLU40C083ltx3cg=='), ('jschl_vc', u'e79dbe851486c8da3857ce74fd44b075'), ('pass', u'1555650677.709-qQIFP/fEcq'), ('jschl_answer', '13.6186827233')])}
2019-04-19 07:11:18,165 (7fb47ffff700) :  DEBUG (logger:28) - urllib3.connectionpool: Resetting dropped connection: subscene.com
2019-04-19 07:11:18,273 (7fb47ffff700) :  DEBUG (logger:28) - urllib3.connectionpool: https://subscene.com:443 "GET /cdn-cgi/l/chk_jschl?s=3f2f9cf24d16afd7eca75809808e2a57e20e64ac-1555650673-1800-AcnjJ51Hp0AZZrd5%2BQ9gVvB45iFmJcBfGPyJEgAxTFYoTX9XsSwHDtdRaEuj3eoB7V%2F1LhjRJqOHi6A9k3Vfmd%2Fts6IybDyjkh%2BerSqh%2FrMo0bi4RWJ5MC5k7%2BScHdV3uZytgZZR5%2FKM4Px0%2FbkflKHE8fCxqn4rN0nGbZIXuBzxPRPK7bzGLU40C083ltx3cg%3D%3D&jschl_vc=e79dbe851486c8da3857ce74fd44b075&pass=1555650677.709-qQIFP%2FfEcq&jschl_answer=13.6186827233 HTTP/1.1" 403 None
2019-04-19 07:11:18,275 (7fb47ffff700) :  ERROR (logger:36) - subliminal_patch.core: Unexpected error in provider 'subscene': Traceback (most recent call last):
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/core.py", line 162, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/subscene.py", line 157, in list_subtitles
    return [s for s in self.query(video) if s.language in languages]
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subliminal_patch/providers/subscene.py", line 219, in query
    film = search(term, session=self.session, release=False)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subscene_api/subscene.py", line 247, in search
    soup = soup_for("%s/subtitles/%s?q=%s" % (SITE_DOMAIN, "release" if release else "title", term), session=session)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/subscene_api/subscene.py", line 58, in soup_for
    html = session.get(url).text
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/cfscrape/__init__.py", line 110, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/cfscrape/__init__.py", line 166, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/cfscrape/__init__.py", line 103, in request
    if self.is_cloudflare_challenge(resp):
  File "/plexmeta/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Libraries/Shared/cfscrape/__init__.py", line 66, in is_cloudflare_challenge
    raise ValueError('Captcha')
ValueError: Captcha
```

There's a couple of debug stuff in there, but what am I missing essentially?

The first one is called from python2.7, the second one is called from the plex environment.

**Comment by pro-src** [comment]
I'm looking into it.

**Comment by pro-src** [comment]
@pannal How are you verifying that it works under py2.7 ? Are you executing the library from this link from the interpreter? I would verify that I'm testing the same version of the library. Do a diff or something to rule that out. Wrong header order: https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/cfscrape/__init__.py#L84

**Comment by pro-src** [comment]
@pannal Also, it's worth noting that the challenges are being solved so that's not the problem. I keep saying cases like this and almost always turns out to be the headers. When you go to reason about this, just know that it's the request info that causing the CAPTCHA, headers, cookies, params, etc. etc. Find out what is different there.

**Comment by VeNoMouS** [comment]
If you're headers do not match the correct ordering or the request, you can wind up with 403's 502's and also captcha that is why the ordering has to be specific .

**Comment by pannal** [comment]
Hey, sorry for the late answer, had to sleep.

I'm currently looking at the differences between the requests - can you spot any?
https://pastebin.com/SdwU0CkU

I can't find a single thing that's different between those two.

**Comment by pannal** [comment]
OK, this is getting weird. Tried another series, and it seems like the challenge went through, but despite being successful, the redirect target then denies it again: https://pastebin.com/r9GcV1KT

**Comment by pro-src** [comment]
Nothing stood out to me but you're trying to work around the real problem which is that Plex's developers don't give a damn about their plugin framework so why would you expect it to work properly? I can't help you with this any further.

Btw nice work on the Sub-Zero channel, it must have been a real pain lol

**Comment by pannal** [comment]
> Btw nice work on the Sub-Zero channel, it must have been a real pain lol

Oh, yes. Had to break out of the sandbox a couple of times to make everything work properly.

I'll try to call a subscript using the system python for CF.

**Comment by pannal** [comment]
@pro-src which UA/header combination would you recommend right now?

**Comment by pro-src** [comment]
@pannal Thought to mention that the new project will have a unit test suite which if you can run it under Plex's environment, maybe you'll be able to better narrow it down.

**Comment by pro-src** [comment]
One of these if you have support for Brotli: https://github.com/pro-src/cloudscraper.js/blob/4.0.0/lib/browsers.json

Otherwise any combination that you copy from a web browser that handles the challenges properly and does not have `br` in the accept-encoding header.

**Comment by pro-src** [comment]
@pannal Just incase you haven't completely given up...lol, Double check your requests version. Make sure it matches this project's requirements and maybe attempt to run their test suite in Plex's environemnt 0.o

**Comment by pannal** [comment]
@pro-src already did ... I'm shipping the current requests version and it gets used by both (local py27 and PMS env).

**Comment by pro-src** [comment]
You ran the unit tests?

**Comment by pannal** [comment]
Ah no, misread that. I'll try running their unittests, fingers crossed that that's possible inside the PMS env.

**Comment by pannal** [comment]
> Edit: I can supply you with a few, if you need them.

Yes, please!

**Comment by pro-src** [comment]
@pannal 
<details>
<summary>Headers (click to expand)</summary><p>

```json
[
  {
    "connection": "close",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "user-agent": "Mozilla/5.0 (Windows NT 5.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.102 Safari/537.36",
    "accept-encoding": "gzip,deflate",
    "accept-language": "en-US,en;q=0.8"
  },
  {
    "connection": "close",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "user-agent": "Mozilla/5.0 (Windows NT 5.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36",
    "accept-encoding": "gzip,deflate",
    "accept-language": "en-US,en;q=0.8"
  },
  {
    "connection": "close",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36",
    "accept-language": "en-US,en;q=0.8",
    "accept-encoding": "gzip, deflate, "
  },
  {
    "connection": "close",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36",
    "accept-language": "en-US,en;q=0.8",
    "accept-encoding": "gzip, deflate, "
  },
  {
    "connection": "close",
    "accept": "*/*",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:30.0) Gecko/20100101 Firefox/30.0"
  },
  {
    "connection": "close",
    "accept": "image/jpeg, image/gif, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, */*",
    "accept-language": "en-US",
    "user-agent": "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
    "accept-encoding": "gzip, deflate"
  },
  {
    "connection": "close",
    "accept": "text/html, application/xhtml+xml, */*",
    "accept-language": "en-US",
    "user-agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)",
    "accept-encoding": "gzip, deflate"
  },
  {
    "connection": "close",
    "accept": "text/html, application/xhtml+xml, */*",
    "accept-language": "en-US",
    "user-agent": "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)",
    "accept-encoding": "gzip, deflate",
    "dnt": "1"
  },
  {
    "connection": "close",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate"
  },
  {
    "connection": "close",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate"
  },
  {
    "connection": "close",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate"
  }
]
```

</p></details>

**Comment by pro-src** [comment]
Notice that the UA's are old, that's because browsers have been supporting Brotli for a while :+1:

**Comment by pannal** [comment]
Thank you!

I seem to have played around too much, though, and I'm now constantly triggering the captcha, even from command line. Time to implement anticaptcha for CF as a fallback :D

**Comment by pannal** [comment]
OK, this definitely is a thing. They're hitting me with a captcha now every single time. Implemented fallback captcha solving, though, and proper headers as well as full header preservation.

If anyone's interested: https://github.com/pannal/Sub-Zero.bundle/commit/9147ed90b702f6a6576c8d377357c7d91e07ab77

**Comment by VeNoMouS** [comment]
Project has been superseded by my other project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).
