### ISSUE TITLE
CF updated ?

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudflare-scrape-js2py#29]
Hello,

I do not know if it is related to #28 or if it is another issue, but some websites do not work anymore, while it was working even since #28 appeared. 

Did you notice a change in CF? if they updated their process ?

here is the log:

```
< GET / HTTP/1.1
< Host: www.japscan.to
< User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Connection: close
< Upgrade-Insecure-Requests: 1
< 

> HTTP/1.1 503 Service Temporarily Unavailable
> Date: Fri, 26 Apr 2019 11:01:23 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=d08d282aa6805daa4f54aba70e6e649b11556276483; expires=Sat, 25-Apr-20 11:01:23 GMT; path=/; domain=.japscan.to; HttpOnly
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 4cd80ef36c09cd08-EWR
> 

Traceback (most recent call last):
  File "japscan.py", line 38, in <module>
    data = getPage().getpage_text(sys.argv[2])
  File "/home/maxx/bin/dl_scripts/CF_getPage.py", line 63, in getpage_text
    ret = cf.get(urlpage, headers=headers, timeout=25)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 107, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 160, in solve_cf_challenge
    redirect = self.request(method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 100, in request
    if self.is_cloudflare_challenge(resp):
  File "/usr/local/lib/python3.6/dist-packages/cfscrape/__init__.py", line 64, in is_cloudflare_challenge
    raise ValueError('Captcha')
ValueError: Captcha
```

If it is related, I will close this thread

**Comment by VeNoMouS** [comment]
There is no js change from what I can see.. it could be related to the other ticket..

**Comment by Krylanc3lo** [comment]
OK, I will close this thread then
